### ISSUE TITLE
images_getInfo fails to parse "long" image IDs

### ISSUE THREAD

**Issue by lokken** [thebeline/SmugWP#1]
Mysteriously, my newly uploaded images to SmugMug were failing to be shown correctly via the SmugWP plugin. I spent a couple hours investigating the code and found that the new images I had uploaded have image IDs that are greater than the max int value so the intval() parsing of the image ID was failing. The fix is just to remove the intval() function call from the $ImageID so that it's just "ImageID" => $ImageID.

<code>function images_getInfo($ImageID, $Password = NULL, $SitePassword = NULL)
    {
        /\* http://smugmug.jot.com/WikiHome/1.2.0/smugmug.images.getInfo */
        $this->request('smugmug.images.getInfo', array("SessionID" => $this->SessionID, "ImageID" => intval($ImageID), "Password" => $Password, "SitePassword" => $SitePassword));
        return $this->parsed_response ? $this->parsed_response['Image'] : FALSE;
    }</code>

**Comment by thebeline** [comment]
Hey, a few years past, but better late than never.  ;-)

**Comment by lokken** [comment]
Haha, that's awesome. Thanks :)

**Comment by thebeline** [comment]
@lokken - That said, this is going to go through a re-factor here in very short order.  A full 2.0 redo, so...  Yeah.

**Comment by lokken** [comment]
Good deal, I'll watch for it.
